version: '3.1'

services:

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'

  wordpress:
    image: wordpress:5.2.3
    stdin_open: true
    tty: true
    restart: always
    ports:
      - 8000:80
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./wordpress:/var/www/html

  adminer:
    image: adminer
    restart: always
    ports:
      - 8001:8080
    depends_on:
      - db

volumes:
  db-volume:

networks:
  postgres:
    driver: bridge
  mongo:
    driver: bridge
